export const StretchFocus = {
  MOBILITY: 'mobility',
  FLEXIBILITY: 'flexibility',
  RECOVERY: 'recovery',
  POSTURE: 'posture',
};

export const defaultStretchLibrary = [
  {
    id: 'neck-release',
    name: 'Neck Release',
    durationSec: 45,
    sideAware: true,
    focus: StretchFocus.RECOVERY,
    intensity: 1,
    cues: ['Drop right ear toward right shoulder', 'Switch sides slowly'],
  },
  {
    id: 'cat-cow',
    name: 'Cat-Cow Flow',
    durationSec: 60,
    sideAware: false,
    focus: StretchFocus.MOBILITY,
    intensity: 2,
    cues: ['Breathe in to arch', 'Breathe out to round the spine'],
  },
  {
    id: 'hip-flexor-lunge',
    name: 'Hip Flexor Lunge',
    durationSec: 60,
    sideAware: true,
    focus: StretchFocus.FLEXIBILITY,
    intensity: 2,
    cues: ['Tuck pelvis gently', 'Keep chest tall'],
  },
  {
    id: 'hamstring-fold',
    name: 'Hamstring Fold',
    durationSec: 60,
    sideAware: false,
    focus: StretchFocus.FLEXIBILITY,
    intensity: 2,
    cues: ['Soft knees', 'Lengthen spine before folding'],
  },
  {
    id: 'thoracic-open-book',
    name: 'Open Book Twist',
    durationSec: 50,
    sideAware: true,
    focus: StretchFocus.POSTURE,
    intensity: 2,
    cues: ['Stack hips', 'Rotate from upper back'],
  },
  {
    id: 'child-pose-lat',
    name: 'Child Pose Lat Reach',
    durationSec: 60,
    sideAware: true,
    focus: StretchFocus.RECOVERY,
    intensity: 1,
    cues: ['Reach fingers long', 'Breathe into side ribs'],
  },
  {
    id: 'figure-four',
    name: 'Figure Four Stretch',
    durationSec: 55,
    sideAware: true,
    focus: StretchFocus.MOBILITY,
    intensity: 2,
    cues: ['Keep ankle flexed', 'Draw legs gently toward chest'],
  },
  {
    id: 'wall-pec',
    name: 'Wall Pec Opener',
    durationSec: 45,
    sideAware: true,
    focus: StretchFocus.POSTURE,
    intensity: 1,
    cues: ['Forearm on wall', 'Turn away slowly'],
  },
];
